### ISSUE TITLE
Jetpack comments support (wordpress.com deployment)

### ISSUE THREAD

**Issue by cherylcolan** [cogdog/splotbox#10]
Hi Alan,

As you know, I recently rolled out SPLOTbox as the theme for [gccazctle.com](https://gccazctle.com), which is hosted on wordpress.com as opposed to self-hosted. Our users are loving it, but one finally reported that they cannot leave a comment. I verified this experience in multiple browsers: the spot to leave a comment was there, but under "Leave a reply" the text box and submit button never loaded.

To troubleshoot, I switched to the Twenty Twenty-One theme to see if comments work (they do). When I switch back to SPLOTbox, they don't work. I realized the problem comes from WordPress.com using Jetpack comments by default.

I reviewed [this support page](https://jetpack.com/support/comments/troubleshooting-jetpack-comments/), which states your theme must use the `comment_form( )` function in your comments.php file - I don't see that file in the SPLOTbox theme.

Per [this support page](https://jetpack.com/support/comments/) I see that Jetpack Comments replace the default comments form, but that they are Opt In - so on our site's dashboard I went to  Jetpack → Settings → Discussion and turned off Jetpack comments. Now our comment form works again.

Including this here as an issue, but you can close it right away if you choose, since it's not an outright problem with the SPLOTbox theme, but rather with its current interaction with Jetpack. I just wanted you to have the option to consider Jetpack comments support. Please let me know if you'd like me to submit a pull request that notes this issue in the theme instructions for WordPress.com users.

**Comment by cogdog** [comment]
Well that's a new one- thanks for doing some checks on this, I've confirmed what you describe in a hosted version with JetPack enabled https://splot.ca/box The use of JetPack's comment options hides the form.

There is a comments.php template- it is in the parent Garfunkel theme. The real test would be if JetPack comments work there, if not, it's the parent theme that is an issue. The SPLOT theme merely checks if the SPLOTbox options are set to allow comments (a more comprehensive switch that the way WP does it) and then uses the Garfunkle theme's capability for managing comments. 

I'm not sure what JetPack does to override the default WP theme, and I can say anyone has asked for it. But I might be persuaded to look deeper when I find a cache of time!

**Comment by cherylcolan** [comment]
Hi Alan,

Thank you for suggesting checking the parent theme. I finally had time to check. The JetPack comments do work with the Garfunkel theme activated. Since I can have comments by deactivating it, I'm in no rush for the JetPack version of comments to work, so don't prioritize that on my account. This issue is closed as far as I'm concerned, but I'm leaving open so you can decide if it's closed for you, too.

**Comment by cogdog** [comment]
Thanks for checking. I'm stumped as SPLOTbox is letting the parent theme manage the comments. I probably will not dig too much farther unless I hear that it's a breaker.
