### ISSUE TITLE
new installation - how to add your content?

### ISSUE THREAD

**Issue by dhattwig** [cogdog/splotbox#12]
First, thank you so much for the SPLOTbox theme! I've successfully added the theme via your impeccable instructions, But the content on your master site isn't included with the theme. Is there an easy way to bring in your example content as well? It is so nice to have a ready-to-go site with content that faculty can see and adapt. Thank you!

**Comment by cogdog** [comment]
Actually it is there just not quite documented, look for the 3 files in the “data” sun directory or get from paid

https://github.com/cogdog/splotbox/tree/master/data

SPLOTbox.xml can be used for doing a WordPress import of content

Install this plugin to set up customized settings
https://wordpress.org/plugins/customizer-export-import/

open customizer and under import, select the customizer.dat file to import settings

Finally, install this plugin to import the widget settings

https://wordpress.org/plugins/widget-importer-exporter/

the file to import is splotbox-widgets.wie

that should get you a copy of the demo site

**Comment by cogdog** [comment]
I guess that helped (or not)

**Comment by dhattwig** [comment]
These steps were perfect and I was able to get a site up and running for a spring quarter class! I ended up using WP All Import<https://wordpress.org/plugins/wp-all-import/> instead of Customizer, but same idea. Thank you so very much for your generous help and time! We would not have been able to do this without your creativity, open sharing, and responsiveness. If you'd like to see what students did with SPLOTbox, their project is called Becoming a Learner<https://uwb.ds.lib.uw.edu/becomingalearner/>. We added a "Reflections" page, & there are some interesting comments from students. Many thanks again!

________________________________

**Comment by cogdog** [comment]
Oh wonderful! I just saw Becoming a Learner this week, and it's now one of my favorite examples.

And good to know that WP All Import was viable. I have been doing some experimentation with creating an import/export capability for the SPLOTbox settings too.

Happy SPLOTting!

**Comment by dhattwig** [comment]
Great, thank you again and cheers!
