### ISSUE TITLE
SPLOT "Share" button has disappeared across all sites

### ISSUE THREAD

**Issue by dhattwig** [cogdog/splotbox#13]
We've just set up another group of students to contribute to [Becoming a Learner](https://uwb.ds.lib.uw.edu/becomingalearner/) at UW Bothell, but found that the "Share" button at the bottom of the "Share" page has disappeared. I checked all of our SPLOTbox sites (hosted by Reclaim), and the "Share" button has disappeared on all SPLOTbox sites. Is it possible that a recent WP update messed up the functionality somehow? Do you have any ideas for a fix to the php or anything else that might get the form functional again? Thank you so much in advance for any suggestions!

**Comment by cogdog** [comment]
Hi, it's more than a missing share button, the bottom part of the form is gone!

This is not an issue with WordPress updating, you will need to update the SPLOTbox theme. Your current version is 3.81 and has an error in it trying to load a placeholder image for the file uploader. The current version is 4.13 and has more bug fixes and some small new features.

You can get the newest version at https://github.com/cogdog/splotbox and download the .zip version from the green code button. Update in WordPress from the Themes area. Click **Add New**, then **upload theme**,  select the .zip file you downloaded. This will then ask you to update SPLOTbox (yes).

Sorry, but this will have to be repeated on each site using the theme-- there is no a means to automatically update these kinds of themes.

That should fix the sites.

**Comment by dhattwig** [comment]
This works seamlessly. Thank you so much for your quick response, clear instructions, and impeccable code! You saved the day for us.

**Comment by cogdog** [comment]
Whew, that makes me happy to hear. I am going to look for some of these SPLOTboxes in the wild.

Actually, there is a means to get automated updates for GitHub housed themes, it makes use of a GitHub Pusher plugin. I ought to do a blog post on this, but details are at https://github.com/cogdog/splotbox#installing-splotbox-in-one-click-with-wp-pusher-get-automatic-updates
