### ISSUE TITLE
feature request - rich text editor

### ISSUE THREAD

**Issue by jrdingwall** [cogdog/splotbox#2]
On the share page, it would be really helpful if the "description" field on the form was a rich text editor.

**Comment by cogdog** [comment]
I'll look into it. I like to think of the broader use cases where some might want a simpler interface. I think I can make it an option: (1) no description field; (2) plain text field; (3) rich text.

**Comment by cogdog** [comment]
Just decided to make any use of the description field use the rich text editor. Added to theme. Give it a test spin at http://splot.ca/box
