### ISSUE TITLE
Customizing the share page throws an error when saving

### ISSUE THREAD

**Issue by robinleung** [cogdog/splotbox#5]
![splotbox-error](https://user-images.githubusercontent.com/8377859/73990145-1d140b00-48fd-11ea-9994-196ad352f984.png)

It won't allow me to save after editing the share page.

**Comment by robinleung** [comment]
In fact, this is widely affected. i.e. can't change colour, can't change header, etc.

**Comment by cogdog** [comment]
Ouch, but I am not able to reproduce errors on any of my test sites. Where is this running (got link?) What version of the SPLOTbox theme?

**Comment by robinleung** [comment]
Hi Alan,

I’m on 2.12 of the theme, hosted on a shared reclaim hosting. On WordPress 5.3.2
https://wordpress.kpu.ca/splotbox/
Appreciate any help in troubleshooting.

Robin

**Comment by cogdog** [comment]
I may have found the problem. I created a new demo site, but forgot that the export file has links to images in the old one, so your site was getting an error on loading the default background image. I restored it.

A help thing is to know how to enable the developers console so you can see errors for files not found, or Javascript errors. That's how I found the missing file problem, It may have messed up the customizer because it was expecting the image (your site will now show the jukebox image i the background, which if it works now, you can change in the customizer).

Sorry about that! I hope this fixes it.

**Comment by robinleung** [comment]
Hi Alan,

I’m not sure if that fixed the problem. I’m still unable to edit the form labels, still the same error.
Awkwardly enough, whenever I submit something through the “share” form it goes to a blank page. Sorry, I’m just not having much luck with this. Would it help, if I reinstall the theme?

R.

**Comment by cogdog** [comment]
Something is amiss. A blank page is usually a PHP error. I downloaded and tested the 2.12 version and have it running ok elsewhere.

Yes, it might be worth a do-over. I just updated the theme as well. If you continue to have issues, it would help to create an admin account for me so I can see if there is anything odd in your set up.

Sorry for hassles.

**Comment by robinleung** [comment]
No, thank you for the responsiveness in helping.
I’m just in the midst of another project today, but hopefully I’ll get back to this one next week. I’m sure you’ll hear from me again.

Cheers,
Robin

**Comment by robinleung** [comment]
Hi Alan,

I’ve reinstalled the theme and it’s looking a lot better! ☺
Basic testing says all is good.

Thanks again for the help.
Robin

**Comment by cogdog** [comment]
That's good to "hear" (and see). have fun with the theme.

**Comment by robinleung** [comment]
Thanks. I am wondering if you had any requests with adding Kaltura videos as part of the list?

**Comment by cogdog** [comment]
No requests for Kaltura, it's likely a more specialized case. 

It will only work if the URL itself can indicate that it's Kaltura content and if there is a regular pattern from the URL for viewing the item that can be used to construct the embed code. Do you have an example?

I have written a plugin that can be used as a template to custom code specialized cases like this
https://github.com/cogdog/splotbox-extender

**Comment by robinleung** [comment]
I did see the splotbox extender.

Example here, https://wordpress.kpu.ca/robin/sample-page/, an embed Kaltura video through oembed which runs by another plugin (attached) and the sample oembed code used: https://media.kpu.ca/id/0_rsydwts9?width=608&height=402&playerId=23448615

Any insights would be great. 😊

Thanks,
Robin

**Comment by cogdog** [comment]
No that's not quite what I mean.

Think of it this way. To autoembed a YouTube URL in WordPress (where you just put a URL on a blan line and it generates the embed code), you put a URL that represents that source page of the video (not one that embeds it), e.g.

https://www.youtube.com/watch?v=JFjigsXHuyY

From that URL alone we can know it is a YouTube video.

It's embed code is:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/JFjigsXHuyY" frameborder="0"></iframe>`

So if I had to write my own code to take the source URL and turn it into embed code, I can see I just need to extract what comes after `v=` and use that to create the iframe code.

For your Kaltura video to work, you would need some kind of public URL that can pull up the video from it's source, then pull out something like an ID, then write the embed code.

Near as I can see from your page source, while this URL _does_ display your video

https://admin.video.ubc.ca/html5/html5lib/v2.76.1/mwEmbedFrame.php/p/150/uiconf_id/23448615/entry_id/0_rsydwts9?wid=_150&iframeembed=true&playerId=kaltura_player&entry_id=0_rsydwts9&flashvars[leadWithHTML5]=true&flashvars[streamerType]=auto&flashvars[localizationCode]=en_CA&flashvars[sideBarContainer.plugin]=true&flashvars[sideBarContainer.position]=left&flashvars[sideBarContainer.clickToClose]=true&flashvars[chapters.plugin]=true&flashvars[chapters.layout]=vertical&flashvars[chapters.thumbnailRotator]=false&flashvars[streamSelector.plugin]=true&flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&flashvars[dualScreen.plugin]=true&flashvars[hotspots.plugin]=1&flashvars[Kaltura.addCrossoriginToIframe]=true&wid=0_37jc5549

That would never be a URL you can use easily to paste in as a source.

It's nit impossible, but would depend on knowing (a) what kind of URL a user would use to represent the video and (b) what the embed code needs to look like. If its a local instance, there is likely some part of that first URL that could be used to say for sure that it is your hosts Kaltura.

**Comment by robinleung** [comment]
Thanks Alan.
Let me chew on that for a bit.

Robin sent the message. Phone sent the typos.

________________________________

**Comment by robinleung** [comment]
Hi Alan,

This is not referring to splotbox but rather the TRUwriter. I must be missing something here, but can you point me in the right direction, I’m trying to get the “Add Media” button to show up in the writing area for non-logged in users. Is that possible?

Thanks,
Robin
[A screenshot of a cell phone  Description automatically generated]

**Comment by cogdog** [comment]
HI Robin,

I moved the issue and answered here https://github.com/cogdog/truwriter/issues/19 In short, look for a new Insert Image button that replaced the media uploader.

**Comment by robinleung** [comment]
Got it! And updated to the newest version.

Thanks,
Robin
